export const defaultTheme = {
  colors: {
    '--white': '#FFFFFF',
    '--background': '#FAFAFA',
    '--card': '#F3F2F2',
    '--input': '#EDEDED',
    '--button': '#E6E5E5',
    '--hover': '#D7D5D5',
    '--label': '#8D8686',
    '--text': '#574F4D',
    '--subtitle': '#403937',
    '--title': '#272221',
    '--purple': '#8047F8',
    '--purple-dark': '#4B2995',
    '--purple-light': '#EBE5F9',
    '--yellow': '#DBAC2C',
    '--yellow-dark': '#C47F17',
    '--yellow-light': '#F1E9C9',
    '--error': 'red',
  },
  textSizes: {
    '--title-XL': '4.8rem',
    '--title-L': '3.2rem',
    '--title-M': '2.4rem',
    '--title-S': '2rem',
    '--title-XS': '1.8rem',
    '--text-regular-L': '2rem',
    '--text-bold-L': '2rem',
    '--text-regular-M': '1.6rem',
    '--text-bold-M': '1.6rem',
    '--text-regular-S': '1.4rem',
    '--text-bold-S': '1.2rem',
    '--components-tag': '1rem',
    '--components-button-G': '1.4rem',
    '--components-button-S': '1.2rem',
  },
  fonts: {
    regular: "'Roboto'",
    title: "'Baloo 2'",
  },
}
